import "./globals.css";
import { Inter } from "next/font/google";
import { SettingsProvider } from "@/components/settings";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <SettingsProvider>
      <html lang="en">
        <body className={`${inter.className} max-w-[70vw] mx-auto`}>{children}</body>
      </html>
    </SettingsProvider>
  );
}
