import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning={true}>
      <body className="prose mx-auto max-w-[900px] dark:prose-invert">
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
